// flow-typed signature: dd749779b4ddbca7a87a41bdbe6991f7
// flow-typed version: <<STUB>>/sass-lint_v^1.12.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sass-lint/bin/sass-lint' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/config-helpers' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/config' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/exceptions' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/groot' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/helpers' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/attribute-quotes' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/bem-depth' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/border-zero' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/brace-style' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/class-name-format' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/clean-import-paths' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/declarations-before-nesting' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/empty-args' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/empty-line-between-blocks' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/extends-before-declarations' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/extends-before-mixins' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/final-newline' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/force-attribute-nesting' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/force-element-nesting' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/force-pseudo-nesting' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/function-name-format' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/hex-length' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/hex-notation' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/id-name-format' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/indentation' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/leading-zero' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/max-file-line-count' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/max-line-length' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/mixin-name-format' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/mixins-before-declarations' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/nesting-depth' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-attribute-selectors' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-color-hex' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-color-keywords' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-color-literals' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-combinators' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-css-comments' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-debug' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-disallowed-properties' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-duplicate-properties' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-empty-rulesets' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-extends' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-ids' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-important' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-invalid-hex' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-mergeable-selectors' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-misspelled-properties' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-qualifying-elements' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-trailing-whitespace' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-trailing-zero' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-transition-all' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-universal-selectors' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-url-domains' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-url-protocols' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-vendor-prefixes' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/no-warn' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/one-declaration-per-line' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/placeholder-in-extend' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/placeholder-name-format' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/property-sort-order' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/property-units' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/pseudo-element' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/quotes' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/shorthand-values' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/single-line-per-selector' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/space-after-bang' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/space-after-colon' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/space-after-comma' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/space-around-operator' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/space-before-bang' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/space-before-brace' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/space-before-colon' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/space-between-parens' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/trailing-semicolon' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/url-quotes' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/variable-for-property' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/variable-name-format' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/rules/zero-unit' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/ruleToggler' {
  declare module.exports: any;
}

declare module 'sass-lint/lib/selector-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sass-lint/bin/sass-lint.js' {
  declare module.exports: $Exports<'sass-lint/bin/sass-lint'>;
}
declare module 'sass-lint/index' {
  declare module.exports: $Exports<'sass-lint'>;
}
declare module 'sass-lint/index.js' {
  declare module.exports: $Exports<'sass-lint'>;
}
declare module 'sass-lint/lib/config-helpers.js' {
  declare module.exports: $Exports<'sass-lint/lib/config-helpers'>;
}
declare module 'sass-lint/lib/config.js' {
  declare module.exports: $Exports<'sass-lint/lib/config'>;
}
declare module 'sass-lint/lib/exceptions.js' {
  declare module.exports: $Exports<'sass-lint/lib/exceptions'>;
}
declare module 'sass-lint/lib/groot.js' {
  declare module.exports: $Exports<'sass-lint/lib/groot'>;
}
declare module 'sass-lint/lib/helpers.js' {
  declare module.exports: $Exports<'sass-lint/lib/helpers'>;
}
declare module 'sass-lint/lib/rules.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules'>;
}
declare module 'sass-lint/lib/rules/attribute-quotes.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/attribute-quotes'>;
}
declare module 'sass-lint/lib/rules/bem-depth.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/bem-depth'>;
}
declare module 'sass-lint/lib/rules/border-zero.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/border-zero'>;
}
declare module 'sass-lint/lib/rules/brace-style.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/brace-style'>;
}
declare module 'sass-lint/lib/rules/class-name-format.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/class-name-format'>;
}
declare module 'sass-lint/lib/rules/clean-import-paths.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/clean-import-paths'>;
}
declare module 'sass-lint/lib/rules/declarations-before-nesting.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/declarations-before-nesting'>;
}
declare module 'sass-lint/lib/rules/empty-args.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/empty-args'>;
}
declare module 'sass-lint/lib/rules/empty-line-between-blocks.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/empty-line-between-blocks'>;
}
declare module 'sass-lint/lib/rules/extends-before-declarations.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/extends-before-declarations'>;
}
declare module 'sass-lint/lib/rules/extends-before-mixins.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/extends-before-mixins'>;
}
declare module 'sass-lint/lib/rules/final-newline.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/final-newline'>;
}
declare module 'sass-lint/lib/rules/force-attribute-nesting.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/force-attribute-nesting'>;
}
declare module 'sass-lint/lib/rules/force-element-nesting.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/force-element-nesting'>;
}
declare module 'sass-lint/lib/rules/force-pseudo-nesting.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/force-pseudo-nesting'>;
}
declare module 'sass-lint/lib/rules/function-name-format.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/function-name-format'>;
}
declare module 'sass-lint/lib/rules/hex-length.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/hex-length'>;
}
declare module 'sass-lint/lib/rules/hex-notation.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/hex-notation'>;
}
declare module 'sass-lint/lib/rules/id-name-format.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/id-name-format'>;
}
declare module 'sass-lint/lib/rules/indentation.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/indentation'>;
}
declare module 'sass-lint/lib/rules/leading-zero.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/leading-zero'>;
}
declare module 'sass-lint/lib/rules/max-file-line-count.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/max-file-line-count'>;
}
declare module 'sass-lint/lib/rules/max-line-length.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/max-line-length'>;
}
declare module 'sass-lint/lib/rules/mixin-name-format.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/mixin-name-format'>;
}
declare module 'sass-lint/lib/rules/mixins-before-declarations.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/mixins-before-declarations'>;
}
declare module 'sass-lint/lib/rules/nesting-depth.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/nesting-depth'>;
}
declare module 'sass-lint/lib/rules/no-attribute-selectors.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-attribute-selectors'>;
}
declare module 'sass-lint/lib/rules/no-color-hex.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-color-hex'>;
}
declare module 'sass-lint/lib/rules/no-color-keywords.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-color-keywords'>;
}
declare module 'sass-lint/lib/rules/no-color-literals.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-color-literals'>;
}
declare module 'sass-lint/lib/rules/no-combinators.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-combinators'>;
}
declare module 'sass-lint/lib/rules/no-css-comments.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-css-comments'>;
}
declare module 'sass-lint/lib/rules/no-debug.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-debug'>;
}
declare module 'sass-lint/lib/rules/no-disallowed-properties.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-disallowed-properties'>;
}
declare module 'sass-lint/lib/rules/no-duplicate-properties.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-duplicate-properties'>;
}
declare module 'sass-lint/lib/rules/no-empty-rulesets.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-empty-rulesets'>;
}
declare module 'sass-lint/lib/rules/no-extends.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-extends'>;
}
declare module 'sass-lint/lib/rules/no-ids.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-ids'>;
}
declare module 'sass-lint/lib/rules/no-important.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-important'>;
}
declare module 'sass-lint/lib/rules/no-invalid-hex.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-invalid-hex'>;
}
declare module 'sass-lint/lib/rules/no-mergeable-selectors.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-mergeable-selectors'>;
}
declare module 'sass-lint/lib/rules/no-misspelled-properties.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-misspelled-properties'>;
}
declare module 'sass-lint/lib/rules/no-qualifying-elements.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-qualifying-elements'>;
}
declare module 'sass-lint/lib/rules/no-trailing-whitespace.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-trailing-whitespace'>;
}
declare module 'sass-lint/lib/rules/no-trailing-zero.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-trailing-zero'>;
}
declare module 'sass-lint/lib/rules/no-transition-all.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-transition-all'>;
}
declare module 'sass-lint/lib/rules/no-universal-selectors.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-universal-selectors'>;
}
declare module 'sass-lint/lib/rules/no-url-domains.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-url-domains'>;
}
declare module 'sass-lint/lib/rules/no-url-protocols.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-url-protocols'>;
}
declare module 'sass-lint/lib/rules/no-vendor-prefixes.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-vendor-prefixes'>;
}
declare module 'sass-lint/lib/rules/no-warn.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/no-warn'>;
}
declare module 'sass-lint/lib/rules/one-declaration-per-line.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/one-declaration-per-line'>;
}
declare module 'sass-lint/lib/rules/placeholder-in-extend.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/placeholder-in-extend'>;
}
declare module 'sass-lint/lib/rules/placeholder-name-format.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/placeholder-name-format'>;
}
declare module 'sass-lint/lib/rules/property-sort-order.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/property-sort-order'>;
}
declare module 'sass-lint/lib/rules/property-units.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/property-units'>;
}
declare module 'sass-lint/lib/rules/pseudo-element.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/pseudo-element'>;
}
declare module 'sass-lint/lib/rules/quotes.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/quotes'>;
}
declare module 'sass-lint/lib/rules/shorthand-values.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/shorthand-values'>;
}
declare module 'sass-lint/lib/rules/single-line-per-selector.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/single-line-per-selector'>;
}
declare module 'sass-lint/lib/rules/space-after-bang.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/space-after-bang'>;
}
declare module 'sass-lint/lib/rules/space-after-colon.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/space-after-colon'>;
}
declare module 'sass-lint/lib/rules/space-after-comma.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/space-after-comma'>;
}
declare module 'sass-lint/lib/rules/space-around-operator.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/space-around-operator'>;
}
declare module 'sass-lint/lib/rules/space-before-bang.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/space-before-bang'>;
}
declare module 'sass-lint/lib/rules/space-before-brace.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/space-before-brace'>;
}
declare module 'sass-lint/lib/rules/space-before-colon.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/space-before-colon'>;
}
declare module 'sass-lint/lib/rules/space-between-parens.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/space-between-parens'>;
}
declare module 'sass-lint/lib/rules/trailing-semicolon.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/trailing-semicolon'>;
}
declare module 'sass-lint/lib/rules/url-quotes.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/url-quotes'>;
}
declare module 'sass-lint/lib/rules/variable-for-property.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/variable-for-property'>;
}
declare module 'sass-lint/lib/rules/variable-name-format.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/variable-name-format'>;
}
declare module 'sass-lint/lib/rules/zero-unit.js' {
  declare module.exports: $Exports<'sass-lint/lib/rules/zero-unit'>;
}
declare module 'sass-lint/lib/ruleToggler.js' {
  declare module.exports: $Exports<'sass-lint/lib/ruleToggler'>;
}
declare module 'sass-lint/lib/selector-helpers.js' {
  declare module.exports: $Exports<'sass-lint/lib/selector-helpers'>;
}
